# Godan server configuration file

[Local]
Host = "0.0.0.0"
Port = "8000"
PrivateKey = "/keys/sample_private.pem"
PublicKey = "/keys/sample_public.pem"

[DB]
Host = "ui_db"
Port = "27017"

[Godan]
Host = "godan_server"
Port = "8080"

[DefaultUser]
Username = "admin"
Password = "admin"
