# Godan worker configuration file

Name = "GodanWorker"

[Rpcmq]
Host = "rabbitmq"
Port = "5672"
Queue = "rpc-msg-queue" 
Exchange = "rpc-exchange"
ExchangeType = "direct" 

[Monmq]
Host = "rabbitmq"
Port = "5672"
Parallel = 50

#[Proxy]
#Host = "localhost"
#Port = "9050"
#Username = "proxy_user"
#Password = "proxy_pwd"
