# Godan worker configuration file

Name = "GodanWorker"

[Rpcmq]
Host = "rabbitmq"
Port = "5672"
Queue = "rpc-queue" 
Exchange = "rpc-exchange"
ExchangeType = "direct" 
Parallel = 50

[Monmq]
Host = "rabbitmq"
Port = "5672"
Exchange = "mon-exchange"

#[Proxy]
#Host = "localhost"
#Port = "9050"
#Username = "proxy_user"
#Password = "proxy_pwd"
